### ISSUE TITLE
R4i 3ds RTS (r4i-sdhc.com) 

### ISSUE THREAD

**Issue by kuwoh** [ntrteam/ds_ntrboot_flasher#23]
says flashcart setup failed (using dsi xl if that gives any more info)
Board revision: B6-v2.7

**Comment by adbash12** [comment]
Same i really need help

**Comment by cachepollution** [comment]
Same here. Tried with 2 different flashcarts (both R4i-SDHC 3DS RTS - board B6-V2.7) on a stock N3DS XL and an original NDS. Both the DS and DSi versions said _flashcart setup failed_. After inserting and removing the flashcarts at different times, I got the flasher to work on the NDS (it flat out refused to recognise the cart on the 3DS) but it always gets stuck at 0% while writing NOR.

Here are the steps to get to the writing NOR part:
1. Boot up the DS mode flasher.
2. Highlight the _R4iSDHC_ entry in the menu. __Don't press A yet__.
3. Take out the flashcart, remove the microSD card and put the cart back in the system.
4. A to continue.
5. A to inject ntrboothax.
6. The next screen says _flashcart press \<A\>_. __Don't press A yet__.
7. Eject the flashcart once again, put it back in and then press A. 
8. A again to inject ntrboothax.
9. A for _RETAIL_ unit (in my case).
10. The flasher gets stuck Writing NOR at 0%.

- If I turn off the DS at step 10 nothing gets written to the cart. It still shows up as Touch! Bomberman Land and boots into the r4i kernel fine.
- I tried using one flashcart to get to step 6 and then swapped it out for my 2nd one to see if it was expecting a different cart than the one used to boot it up. Still didn't work.
- I also tried leaving the console on for 30'+ but it never went beyond 0%.

**Comment by Parpalloto** [comment]
Exactly what I did on mine and it didn't work either.

**Comment by grilledpineapple** [comment]
Yup flashcart setup failed on a 3DS.

**Comment by knowbeard** [comment]
Tried 2 RTS lite flashcards on 2 DS lites and had the exact same results as you.

**Comment by WereWaffle** [comment]
tested my r4i 3ds rts card with ak2i_ntrcardhax_flasher dsi .nds. Experienced the same problem as OP.

**Comment by kuwoh** [comment]
@cachepollution followed your steps still gives me flashcart failed, tried on my 2ds and dsi xl

**Comment by cachepollution** [comment]
@kuwoh The steps only seem to work on an _original_ DS. I couldn't get it to work on my 3DS no matter what. Maybe it has something to do with the firmware on newer consoles?

**Comment by kuwoh** [comment]
sadly i do not have access for original ds consoles

**Comment by cachepollution** [comment]
Did you try the DS flasher? The DSi one seems to be completely broken. I guess we'll have to wait until the issue gets fixed. Besides, even if you did manage to get to step 10, it still wouldn't flash anything to the cart. Perhaps someone with an original DS or a DS Lite could test the steps to see if they get a different result?

**Comment by kuwoh** [comment]
yes i've tried the ds flasher multiple times on both of my systems, sadly i do not know anyone with an original ds or ds lite console

**Comment by ocedalv** [comment]
I was able to reproduce the same issue, but my cart is a R4 SDHC Gold Pro 2016 (from r4sdhc.com). I am able to flash and restore using NTRBOOT_FLASHER, but not using AK2I.

**Comment by MilkyPL** [comment]
I have the same problem on r4isdhc.com dual core rts on old 2ds

**Comment by KonzolozZ** [comment]
Problem is same with RTS Lite 2017 on DS and DS Lite.

**Comment by Parpalloto** [comment]
I have tried it on a R4i SDHC RTS Lite on an original NDS, a NDSI and a N3DS and it didn´t work.

**Comment by Shymain** [comment]
Can confirm same problem persists with R4i SDHC Dual-Core RTS from r4isdhc.com

**Comment by d3m3vilurr** [comment]
can you retest with latest release?

**Comment by demonfurry** [comment]
having same issue as OP using n3ds xl, r4i-sdhc rts same board revision even with the latest release

**Comment by kuwoh** [comment]
^^

**Comment by Rikimaruaxu** [comment]
Same here. R4I SDHC dual core RTS freezes when you select the flashcart type on a Nintendo DS lite.

**Comment by cachepollution** [comment]
Nope. Still no luck with v3.3. The DSi flasher fails to recognise the cart on N3DS and the DS flasher crashes upon launch, both on the NDS and the N3DS.

**Comment by ocedalv** [comment]
Similar result for me as @cachepollution 

N3DS with DSI flasher fails to recognize the cart.
NDS with regular (non-DSi) flasher launches but freezes when I eject the cart / microSD as instructed.

**Comment by ocedalv** [comment]
Similar result to @cachepollution 

N3DS with DSi flasher fails to recognize the cart.
NDS with regular (non-DSi) flasher launches but freezes after I select the family of carts, when I eject the cart / microSD as instructed.

**Comment by knowbeard** [comment]
Tried 2 different "2017 RTS lite r4isdhc.com B6 V2.8" cards with the nds flasher (non dsi) on a ds lite and I get the same results as @ocedalv and @cachepollution.

**Comment by grilledpineapple** [comment]
Tried the newest release on my R4i-SDHC 3DS RTS and O3DS. Still getting Flashcart setup failed for both the NDS and DSi version. Even tried ejecting and removing the SD card.

**Comment by yoshigamer478** [comment]
i get issue well trying to flash the R4i 3DS RTS on the latest relase of the ak2i_ntrcardhax_flasher using my orignal nintendo Ds heres the problem the program on the ds loads up fine but when you eject the flash cart out of the DS and take out the Micro SD card and put the Flash cart back into the Ds and hit A on the R4I SDHC family option it just Freezes and dose nothing and i tryed it many time and no luck i even tried the DSI ak2i_ntrcardhax_flasher on my 3ds but it just says flash cart fails setup

**Comment by d3m3vilurr** [comment]
actually, 3.3 version cannot support r4i sdhc. it occur [last commit](https://github.com/kitling/flashcart_core/commit/46f650b00d563b354b5c4596352f624a66e605a0) of flashcart_core.
this commit will support old r4i sdhc, but now requires flashcart reset (not softly)
problem is, I don't know right ds steps like 3ds's flashcart reset steps.
I need more time. sorry.

**Comment by cachepollution** [comment]
Does this mean that the last commit to flashcart_core broke the flasher or did it actually add support for r4i-sdhc _for the first time_ on the NDS? In other words, could releases prior to v3.3 theoretically support ntrboot injection on these flashcarts? Or is it only possible after the last commit?

**Comment by MilkyPL** [comment]
How can i reset the flashcart using 3ds?

**Comment by d3m3vilurr** [comment]
@cachepollution 
1. last commit only broke nds version & actually prev commit can support r4i sdhc (but partially).
2. so theoretically I can release with prev commit but I'll try to fix with current commit until I gave up.

@MilkyPL [here](https://github.com/kitling/ntrboot_flasher/blob/ce47ce0/source/platform_ntrcard.cpp#L69-L105)

**Comment by Shymain** [comment]
Problem still exists on my end with v3.3, R4i SDHC Dual-Core RTS 2016 for 3DS from r4isdhc.com.

**Comment by cachepollution** [comment]
@d3m3vilurr I see. Thanks for clearing that up. Guess it's best to stick to the newer commits then.

**Comment by Virgilius1995** [comment]
Same issue with http://r4i-sdhc.com/
Any alternative software?

**Comment by agescospreader** [comment]
i have same issue with r4i rts 3ds r4i-sdhc.com   flashcart setup failed

**Comment by d3m3vilurr** [comment]
if someone have a time, please test this & copy log messages
[ak2i_ntrcardhax_flasher_dsi.nds.zip](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/files/1402932/ak2i_ntrcardhax_flasher_dsi.nds.zip)

**Comment by tomsterley** [comment]
R4 SDHC RTS GOLD PRO (with sd inserted, tested on dsi with dsi flasher)

flags: 5406020 1 0 1
Sending cmd: 99 01 04 00 00 00 00 00
flags: 7586000  1 0 1
step 0: c074666

Flashcart setup failed

**Comment by ocedalv** [comment]
I have a R4i Gold Pro 2016 (r4isdhc.com)
Here we go:

flags 5406020 1 0 1

Sending cmd: 99  01  04  00 00 00 00 00

flags 7586000 1 0 1

setp 0: 92224D68

flashcart setup failed

**Comment by d3m3vilurr** [comment]
please retest with this.

[ak2i_ntrcardhax_flasher_dsi.nds.zip](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/files/1402987/ak2i_ntrcardhax_flasher_dsi.nds.zip)

**Comment by tomsterley** [comment]
@d3m3vilurr 
R4i SDHC RTS GOLD PRO 2017 [r4isdhc.com](with sd inserted, tested on dsi with dsi flasher)

Retest with new file

flags: 5406020 1 0 1
Sending cmd: 99 01 04 00 00 00 00 00
flags: 7586000 1 0 1
Step 0: dee7a45f

Flashcart setup failed

**Comment by cachepollution** [comment]
Tested with R4i-SDHC 3DS RTS on N3DS.

`flags 5406020 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7586000 1 0 1`
`step 0: B72DA6BB`
`Flashcart setup failed`

**Comment by d3m3vilurr** [comment]
here please retest.
[ak2i_ntrcardhax_flasher_dsi.nds.zip](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/files/1403014/ak2i_ntrcardhax_flasher_dsi.nds.zip)

**Comment by ocedalv** [comment]
I have a R4i Gold Pro 2016 (r4isdhc.com)

flags 5406020 1 0 1
sending cmd: 99 01 04 00 00 00 00 00
flags 7586000 1 0 1
step 0: 5d06f072

Flashcart setup failed

**Comment by d3m3vilurr** [comment]
@ocedalv  you looks not last one.

**Comment by tomsterley** [comment]
@d3m3vilurr 
R4i SDHC RTS GOLD PRO 2017 [r4isdhc.com](with sd inserted, tested on dsi with dsi flasher)

Retest with new file 2

flags: 5406020 1 0 1
Sending cmd: 99 01 04 00 00 00 00 00
flags: 7586000 1 0 1
step 0: b3105a3e
Sending cmd: 68 00 00 00 00 00 00 00
flags: 75860000 1 0 1
Sending cmd: 99 01 04 00 00 00 00 00
flags: 7180000 0 0 1
step 1: 0 (Press A)
FLASHCART INIRIALIZE FINISHED
PRESS A
<dsi shutsdown>

**Comment by d3m3vilurr** [comment]
@tomsterley that's totally what I need. I made to kill at that time. because I'm not finished yet :)

**Comment by cachepollution** [comment]
Retest results:

`flags 5406020 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7586000 1 0 1`
`step 0: 892CF327`
`Sending cmd: 68 00 00 00 00 00 00 00`
`flags 7586000 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7180000 0 0 1`
`step 1: 0`
`FLASHCART INITIALIZE FINISHED!!!`

And then the flasher quits when I press A.

**Comment by tomsterley** [comment]
@d3m3vilurr Ah ok, I didnt know if the dsi shutting down was ok or not

**Comment by ocedalv** [comment]
I have a R4i Gold Pro 2016 (r4isdhc.com), using O3DS @ 11.6 (U)

flags 5406020 1 0 1
sending cmd: 99 01 04 00 00 00 00 00
flags 7586000 1 0 1
step 0: 192fe428
sending cmd: 68 00 00 00 00 00 00 00
flags 7586000 1 0 1
sending cmd: 99 01 04 00 00 00 00 00
flags 7180000 0 0 1
step 1: 0
FLASHCART INITIALIZE FINISHED!!!

Flasher quits when A is pressed.

**Comment by agescospreader** [comment]
R4i-sdhc 3ds rts (r4i-sdhc.com)
flags 5406020 1 0 1
press A
sending cmd: 99 01 04 00 00 00 00 00
press A
flags 7586000 1 0 1
press A
step 0: FCE2F045
press A
sending cmd: 68 00 00 00 00 00 00 00
press A
flags 7586000 1 0 1
press A
sending cmd: 99 01 04 00 00 00 00 00
press A
flags 7180000 0 0 1
press A
step 1: 0
press A
flashcart initialize finished !!!
press A
software closed

**Comment by tomsterley** [comment]
@d3m3vilurr Any idea when a full release will be ready?

**Comment by trbocode** [comment]
He uploaded this on discord, try this. Please test only if you have a hacked 3DS.
[ak2i_ntrcardhax_flasher_dsi.zip](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/files/1403142/ak2i_ntrcardhax_flasher_dsi.zip)

**Comment by tomsterley** [comment]
@trbocode This actually worked!

**Comment by ocedalv** [comment]
@trbocode worked for me too!

**Comment by agescospreader** [comment]
worked for me to

**Comment by zacharypsp** [comment]
What would happen if you didn't have a hacked 3 ds and flashed it trbocode

**Comment by zacharypsp** [comment]
It seems to have flashed properly but i cant seem to get it to boot in gm9

**Comment by ocedalv** [comment]
@zacharypsp you have to rename it to boot.firm and put it in the root of the SD card. but this thread is not for this kind of support, please use the discord channel:

https://discord.gg/C29hYvh

**Comment by demonfurry** [comment]
the link from trbocode worked great on my bone stock new3dsxl and the r4i-sdhc RTS card currently finishing installing everything

**Comment by grilledpineapple** [comment]
@demonfurry Same thing here. Just used my R4i-SDHC 3DS RTS on a stock o3DS. Thanks a lot to every one who helped bringing this to life.

**Comment by yoshigamer478** [comment]
@demonfurry @grilledpineapple so it worked for you guys you where able to flash the R4I SDHC 3DS RTS fine so should it be ok for me to do it on my stock 3ds

**Comment by Hoshimon** [comment]
I tried flashing that on mine and the touch screen went black while the first step was still at 0%, dunno what happened. (R4iGold.cc, totally a SDHC clone)

**Comment by Shymain** [comment]
New file worked fine for my flash cart (R4i SDHC Dual-Core RTS 2016 for 3DS from r4isdhc.com)! Thank you so much!

**Comment by grilledpineapple** [comment]
@yoshigamer478 Yup just finished setting it up on my previously unhacked 3DS. Here's the backup I used to restore if you need it.
[R4i-SDHC Backup.zip](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/files/1403630/R4i-SDHC.Backup.zip)

**Comment by yoshigamer478** [comment]
@grilledpineapple thank you so much

**Comment by zacharypsp** [comment]
after replacing my boot.firm on my o3ds (unhacked) flashed with same o3ds it booted up into safeb9installer so i can confirm that r4i-sdhc rts B6-v2.5 B13 it is working on

**Comment by yoshigamer478** [comment]
I can confirm that the new file that got posted in chat worked great I was able to flash the flash the R4I SDHC 3DS RTS card and was able to install safeB9s installer then luma with no problem at all

**Comment by d3m3vilurr** [comment]
I need someone who goes step 2 at the chip detection with my [last comment](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/issues/23#issuecomment-33829585) version(not the @trbocode's comment)

please share the log result.

**Comment by d3m3vilurr** [comment]
@angelsl shared target cart info: r4isdhc 2014
if you have that, please share result whenever success or not

**Comment by trbocode** [comment]
@Hoshimon the r4igold.cc is a different cart

**Comment by patrizl001** [comment]
@d3m3vilurr here's mine, R4i 1.4.1
flags 5406020 1 0 1
Sending cmd: 99 01 04 00 00 00 00 00
flags 7586000 1 0 1
step 0: 866348A2
Sending cmd: 68 00 00 00 00 00 00 00
flags 7586000 1 0 1
Sending cmd: 99 01 04 00 00 00 00 00
flags 7180000 0 0 1
step 1: 0
FLASHCARD INITIALIZE FINISHED!!!

**Comment by cachepollution** [comment]
@d3m3vilurr Good news. I managed to get to step 2 after messing around with your flasher for a little while. It only works with my original DS (on 3DS it always stops at step 1) and I had to take out the flashcart __and the microSD__ and then put the cart back in before starting the process (pretty much like steps 1-4 in [this comment](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/issues/23#issuecomment-336722835)). And even though this is the DSi flasher, you need to remove the flashcart and put it back in without the microSD card to get it to work.

Here's the log:
`flags 5406020 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7586000 1 0 1`
`step 0: 203FCB38`
`Sending cmd: 68 00 00 00 00 00 00 00`
`flags 7586000 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7180000 0 0 1`
`Sending cmd: 66 00 00 00 00 00 00 00`
`flags 7586000 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7180000 0 0 1`
`step 2(0): FFFFFFFF`
`Sending cmd: 66 00 00 00 00 00 00 00`
`flags 7586000 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7180000 0 0 1`
`step 2(1): FFFFFFFF`
`Sending cmd: 66 00 00 00 00 00 00 00`
`flags 7586000 1 0 1`
`Sending cmd: 99 01 04 00 00 00 00 00`
`flags 7180000 0 0 1`
`step 2(2): FFFFFFFF`
`Flashcart setup failed`

What's interesting is that it seems to skip step 1 altogether and go directly to step 2 with this method. Is this intended behaviour?

**Comment by d3m3vilurr** [comment]
@cachepollution why you redefine job steps?

**Comment by cachepollution** [comment]
If I do this, then the output is the same as in [this comment](https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/issues/23#issuecomment-338297661). It completes step 1 and gives me the flashcart initialise finished message but it never gets to step 2. However, using the other method it seems to skip step 1 and go to step 2.

**Comment by d3m3vilurr** [comment]
@cachepollution because your cart is not old type. and that is normal.
I need testing result with controlled environ. eject cart makes the corrupt result.

**Comment by cachepollution** [comment]
Oh I see. My bad. I thought your request was separate from your next comment, which specified the target cart. Sorry!

**Comment by MilkyPL** [comment]
Flasher from @trbocode worked and i succesfully installed b9s and luma on my unhacked 2ds. Thanks!

**Comment by vikingo87** [comment]
I can confirm tah flasher posted by @trbocode works whit no problems for my R4i SDHC Dual-Core 2014 from www.r4isdhc.com. It worked in my unhacked Old 3ds  (11.6). I susuccesfully installed b9s, luma, goodmode9, fbi, etc. Thaks you all!!  This was the only flasher that works whit my card.

**Comment by knowbeard** [comment]
Tried 2 different "2017 RTS lite r4isdhc.com B6 V2.8" cards with the launcher @trbocode linked on a stock 2ds and used it to unbrick 2 o3ds and perform ctrtransfer on both. Thanks to all devs involved. This should work on all SDHC.COM cards released from 2014 onwards, check the motherboard and check to make sure it looks the same if you have no way of restoring the card.

**Comment by MarioMasta64** [comment]
also as a note you may want to use [ysmenu](https://gbatemp.net/download/retrogamefan-multi-cart-update.35737/) instead of the stock firmware as the restore using the nor worked for me however booting the cart up gives the message that it is not a legit cart and to return to the retailer (along with trying to corrupt the sd card a bit, which is kinda very mean if its on purpose) (referring to #26 sorry)
