### ISSUE TITLE
R4isdch dual core setup failed

### ISSUE THREAD

**Issue by rjose2002** [ntrteam/ds_ntrboot_flasher#25]
have a r4i dual core that worked with ntrboot_flasher and doesn't work with the dsi one

**Comment by benji200** [comment]
i have r4 dual core 2013 with the page in www.r4isdhc.hk and dont work with ntrboot flasher and dsi , is this card, sorry for my bad english, idont speak english, im a mexicano, o sea que hablo español
![22554465_125084551528023_484027257_n](https://user-images.githubusercontent.com/32855107/31639933-171dd48c-b2a1-11e7-8f39-c6780f5edc41.jpg)

**Comment by benji200** [comment]
r4 dual core 2013 
windbond
25Q16BVSIG1236
-----------
PD910B
1304
-----------
203K
KR465

**Comment by rjose2002** [comment]
Needs to say R4isdhc.con front and back, other doesn't work at least with flasher
![img-20171015-wa0002](https://user-images.githubusercontent.com/32212336/31640085-9306b614-b2dc-11e7-8968-24b16cf78eab.jpg)

**Comment by d3m3vilurr** [comment]
please retest with latest release.

**Comment by SohaibArif** [comment]
It's not working on 2016 Variant tried both the NDS as well as DSi file.

**Comment by SohaibArif** [comment]
I am using v3.9 firmware on the flashcart .The website mentioned on the card is www.r4isdhc.com

**Comment by SohaibArif** [comment]
![screenshot_2017-10-17-10-47-33](https://user-images.githubusercontent.com/32861218/31648791-1f265658-b329-11e7-9c33-df65e6db342d.png)

**Comment by yitzh** [comment]
apparently it can only be with ntrboot_flaser for now

**Comment by jason0597** [comment]
Try the experimental flasher, it should work
(Note: Proceed at your own risk!)

https://github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/files/1403142/ak2i_ntrcardhax_flasher_dsi.zip

**Comment by zarzarzarzar** [comment]
The link that @jason0597 gave worked for me and I installed the cfw without problems

**Comment by Virgilius1995** [comment]
Hey thanx it worked(-;

**Comment by d3m3vilurr** [comment]
okay, comments don't match the first report.
