### ISSUE TITLE
ak2i not showing R4i-SDHC 3DS RTS as option.

### ISSUE THREAD

**Issue by SlothNationn** [ntrteam/ds_ntrboot_flasher#32]
When I try to do step 3 on section 2 of [https://3ds.guide/flashing-ntrboot-(nds)](url) it does not show the [http://www.nds-card.com/ProShow.asp?ProID=146](url) flashcart as an option.

**Comment by SlothNationn** [comment]
oh, and when I try all the other 3 shown flashcarts, it says boot failed or something.

**Comment by jason0597** [comment]
You may have to use the experimental flasher to get your flashcart working with ntrboot, as the current latest official release isn't compatible yet.
