### ISSUE TITLE
Got R4iGold 3DS (r4igold.cc) (that should be a SDHC clone) not working.

### ISSUE THREAD

**Issue by Hoshimon** [ntrteam/ds_ntrboot_flasher#33]
As the title says, I got a flashcard that other people has described and found to be an SDHC clone, and it's not working, here's some photos of the outside of the flashcard.
If it's proven to be interesting enough, I can open it to take photos of the inside of the cart, and I can provide whatever info's possible to get with just a normal 3DS (magnethax might be first chance I get to actually hack since I got interested on the matter).

The actual problem when running the flasher is that all setups say "Flashcart setup failed press <A>".

![fullsizerender-1](https://user-images.githubusercontent.com/19254280/31842403-5a04f066-b5c4-11e7-8d97-4026ba6f7060.jpg)
![fullsizerender](https://user-images.githubusercontent.com/19254280/31842405-5a294c36-b5c4-11e7-8c8f-a3ceae3bda7d.jpg)

Thanks beforehand for any help I could get or could give.
Loving how big magnethax has been for a lot of people! <3

**Comment by Hoshimon** [comment]
I saw over at //github.com/d3m3vilurr/ak2i_ntrcardhax_flasher/issues/23# an upload from trbocode that actually "starts" flashing, but after a second or two the bottom screen goes black and nothing happens until you restart, maybe that's helpful in some way?

**Comment by jason0597** [comment]
Does ntrboot_flasher support this flashcart? From what I recall, the only working flasher is that modified chinese version on gbatemp that cannot be reverted

**Comment by trbocode** [comment]
@Hoshimon it doesn't remotely look like an r4isdhc clone
This the R4isdhc https://user-images.githubusercontent.com/8488758/31848053-2206923e-b63a-11e7-8485-c51954582cb2.png

**Comment by Hoshimon** [comment]
It does look really differently, I went with it being a SDHC clone since I saw a lot of forums with these r4igold.cc with years engraved into them that went as SDHC clones.
Also the SDHC menu in ntrboot flasher is the only one that goes throught.
Guess It's just out of compatibility then.
I know people have already too much on their hands with this, but is there any info I can give so this could have support in the future?
I don't know if this cheap flashcard might be interesting to provide support too, I only know these sell commonly in Latin America for like 10 bucks (at least in Chile).

Thanks for the answer!

**Comment by Hoshimon** [comment]
@jason0597 It's supposed to work, but it actually doesn't flash anything at all, just reboots.
This made me think that either the card is a clone of anything but the r4igold.cc or that the flashcard itself is unflashable.
Thanks for the answer!

**Comment by d3m3vilurr** [comment]
this chip isn't r4i sdhc. current flashcart_core does not support this.

**Comment by jason0597** [comment]
Refer to this post:

https://gbatemp.net/threads/release-ntrboot-for-r4igoldcc-ards-ez-ardsi.483802/

**Comment by d3m3vilurr** [comment]
ntrteam/flashcart_core#33

**Comment by RisingSoul526** [comment]
Try this karnets [http://www.r4igold.cc/3ds_download.asp](url)

**Comment by Omiclous** [comment]
hola, tengo la misma r4, luego de 5 años me dispuse a arreglarla, cómo lo conseguiste?
