### ISSUE TITLE
r4sdhc stup failed

### ISSUE THREAD

**Issue by Bagou450** [ntrteam/ds_ntrboot_flasher#35]
r4sdhc stup failed 
i have a dual core r4 sdhc card 2017 i have followed the tutorial of 3ds.guide and https://www.youtube.com/watch?v=9lD_x2semvQ&t=304s but each time i choose my card so r4 sdhc and it's my setup failed
or I buy the r4 :  http://www.r4wood.com/products/R4-SDHC-Dual-Core-for-3DS-XL-LL-3DS-2DS-DSi.html 
the firmware inclued
my version of 3ds : new 3ds 11.5.0-38E

**Comment by yavier2327** [comment]
i have exactly the same issue, i have the version 11.6 :/

**Comment by jason0597** [comment]
The flasher will **not work** with r4isdhc.hk or r4isdhc.com.cn flashcarts. It will **only** work with r4isdhc.com or r4i-sdhc.com flashcarts.

**Comment by rswsc0407** [comment]
I've done the exact same thing and I can't seem to get it to work either. My card says www.r4i-sdhc.com too.

**Comment by yavier2327** [comment]
in this thread R4i 3ds RTS (r4i-sdhc.com) bug
#23 opened 9 days ago by kuwoh  there is the solution

**Comment by Bagou450** [comment]
can you update it to make it compatible?

**Comment by Bagou450** [comment]
she walks? http://www.nds-card.com/ProShow.asp?ProID=490
elle marche ellle

**Comment by d3m3vilurr** [comment]
if still not work, reopen issue
