### ISSUE TITLE
 she walks?

### ISSUE THREAD

**Issue by Bagou450** [ntrteam/ds_ntrboot_flasher#40]
she walks? for hack?

http://www.r4sdhc3ds.com/r4-3ds/13-r4i-sdhc-silver.html

I'm in 15.0-38th something like that

**Comment by jason0597** [comment]
Yes this one will work.

Please do not use the issue tracker to ask for assistance on how to use this software. The issue tracker is only for keeping track of bugs or suggestions for the code. If you need assistance, go to https://discord.gg/C29hYvh

**Comment by jason0597** [comment]
@d3m3vilurr Can this issue be closed?
