### ISSUE TITLE
r4 sdhc dual core 2017 error

### ISSUE THREAD

**Issue by agen4er** [ntrteam/ds_ntrboot_flasher#43]
When i press retail a text appears saying writing blowfish (1) 0% then another text flashes which is unreadable and then the bottom screen goes completely black without making any progress

**Comment by jason0597** [comment]
Is this flashcart `r4isdhc.com`? Or is it `r4isdhc.hk` / `r4isdhc.com.cn` ?

**Comment by agen4er** [comment]
.com .cn

**Comment by jason0597** [comment]
.com.cn flashcarts are unsupported for ntrboot.
Please close this issue, and refer to https://github.com/ntrteam/flashcart_core/issues/33

**Comment by panos4** [comment]
r4isdhc.com.cn never supported for ntrboot????

**Comment by panos4** [comment]
i buy r4isdhc.com.cn and i have the same problem....what i can do???

**Comment by jason0597** [comment]
@panos4 You can wait for it to be supported.

**Comment by panos4** [comment]
With an update???

Στις 20 Νοε 2017 17:39, ο χρήστης "jason0597" <notifications@github.com>
έγραψε:

**Comment by jason0597** [comment]
Are you Greek?

Εάν εισαι, τοτε εχω να σου πω πως πρεπει να περιμενεις για καινουργιο update για αυτα τα εργαλεία για hacking

**Comment by panos4** [comment]
Ναι Έλληνας ειμαι!
Που μπορώ να ενημερώνομαι για τα καινούργια update? Μολις σήμερα αγόρασα
αυτην την flashcard και παιδευομαι όλη μέρα....

Στις 20 Νοε 2017 17:43, ο χρήστης "jason0597" <notifications@github.com>
έγραψε:

**Comment by jason0597** [comment]
Οπως σου εχω πει, αυτη η r4 δεν υποστηρίζεται απο το ntrboot, θα πρεπει να περιμένεις να υποστηριχτεί

Sorry for this d3m3

**Comment by d3m3vilurr** [comment]
yeah please use eng.

**Comment by jason0597** [comment]
@d3m3vilurr but yeah, you can close this issue as it is a flashcart_core issue

**Comment by panos4** [comment]
What this mean???
