### ISSUE TITLE
R4i SDHC Dual Core 2016 - "Flashcart setup failed" after 3 tries

### ISSUE THREAD

**Issue by 123321mario** [ntrteam/ds_ntrboot_flasher#44]
I got this message everytime please help ! I'm on a New 3DS XL
![](https://cdn.discordapp.com/attachments/256301586421252096/381395369495625728/image.png)

**Comment by jason0597** [comment]
Is this flashcart `r4isdhc.com`? Or is it `r4isdhc.hk` / `r4isdhc.com.cn` ?

**Comment by jason0597** [comment]
@123321mario

**Comment by 123321mario** [comment]
Oh crap sorry i didn't see your message, unfortunately i lost the label but, the cart circuits are not exactly the same as the official ones. After some research i found  people having the exact same cart and it's labelled www.r4isdhc.com.cn .

**Comment by jason0597** [comment]
@123321mario try dumping the flash with [this](https://cdn.discordapp.com/attachments/356378901250834434/389425509307645952/ntrboot_flasher_nds.nds) flasher, by choosing the ace3ds plus option

make sure to set the log level to debug before choosing ace3dsplus

**Comment by 123321mario** [comment]
It created me a folder and there's the content : 
[ntrboot.zip](https://github.com/ntrteam/ds_ntrboot_flasher/files/1548814/ntrboot.zip)
(it was not a zip file but it's content)

**Comment by jason0597** [comment]
@123321mario [Download boot9strap_ntr](https://github.com/SciresM/boot9strap/releases/download/1.3/boot9strap-1.3-ntr.zip), and from that zip, take the `.firm` file and put it in the `ntrboot` folder that's on your flashcart's SD card.

Afterwards, boot into the flasher again, set the log level to debug, select ace3ds, and then select "Inject FIRM"

Once it finishes and kicks you back to the main menu, shut down the console, and then follow this guide:
https://3ds.guide/installing-boot9strap-(ntrboot)

**Comment by 123321mario** [comment]
Thanks a lot ! It worked ! But now I Want to recover my card but the flasher don't recognize my flashcard i tried all options nothing works

**Comment by jason0597** [comment]
You're following the section for restoring the flashcart that's on the guide, right?
If so, what flash dump were you planning on using? The one you uploaded earlier?

**Comment by 123321mario** [comment]
Yes the one i've uploaded.

**Comment by jason0597** [comment]
Try using this flasher instead to restore it:
https://www.dropbox.com/s/fz187pirzqgkj3x/ntrboot_flasher.firm?dl=0

**Comment by 123321mario** [comment]
I will try it tomorrow, it's late :)

**Comment by 123321mario** [comment]
It's working ! Thanks you for all !
Did you have a discord server to recommend me if I have others problems?
I'm on the Nintendo Homebrew one

**Comment by jason0597** [comment]
@123321mario I can recommend you gbatemp (not a discord server), they can help you if you ever have an issue

Apart from that, the issue has been resolved now, so, I suggest closing it

**Comment by 123321mario** [comment]
ok i will check it out, i'm closing the issue ;)
