### ISSUE TITLE
R4 SDHC Dual Core smart update 2017

### ISSUE THREAD

**Issue by panos4** [ntrteam/ds_ntrboot_flasher#47]
will be support with an update to ntrboothax soon?????
(www.r4sdhc.com.cn)

**Comment by jason0597** [comment]
This is not the place to be asking for this. If you want to keep up with the latest updates on whether this flashcart will get supported, refer to https://github.com/ntrteam/flashcart_core/issues/33

Translation for you @panos4 is at: https://hastebin.com/ujivixiqor.erl

**Comment by jason0597** [comment]
@d3m3vilurr Can this issue be closed?

**Comment by jason0597** [comment]
@panos4 do you have a gbatemp account or a discord account?

**Comment by panos4** [comment]
No but i can try to create one....

Στις 17 Δεκ 2017 5:31 ΜΜ, ο χρήστης "jason0597" <notifications@github.com>
έγραψε:

@panos4 <https://github.com/panos4> do you have a gbatemp account or a
discord account?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ntrteam/ds_ntrboot_flasher/issues/47#issuecomment-352263823>,
or mute the thread

**Comment by jason0597** [comment]
@panos4 https://discordapp.com/register?redirect_to=%2F make an account, and then tell me your name
it will be on the bottom left corner, and it will have a # with 4 numbers after it

**Comment by panos4** [comment]
panos444#1047

Στις 17 Δεκ 2017 5:46 ΜΜ, ο χρήστης "jason0597" <notifications@github.com>
έγραψε:

**Comment by ghost** [comment]
@jason0597  actually, if you have a GBATemp account, can you pm me? I have some questions about the new nds flasher

**Comment by panos4** [comment]
Οκ

Στις 17 Δεκ 2017 10:11 ΜΜ, ο χρήστης "zacchi4k" <notifications@github.com>
έγραψε:

**Comment by jason0597** [comment]
PM MrJason005

17 Δεκ 2017, 8:11 μμ, ο χρήστης «zacchi4k <notifications@github.com<mailto:notifications@github.com>>» έγραψε:


@jason0597<https://github.com/jason0597> actually, if you have a GBATemp account, can you pm me? I have some questions about the new nds flasher
